# Generated by Django 2.2.4 on 2019-09-11 01:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('created', models.DateField(verbose_name='Created')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Rocation')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InfoTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID number')),
                ('itname', models.CharField(max_length=64, verbose_name='Name')),
                ('itlocationname', models.CharField(max_length=64, verbose_name='Rocation Name')),
                ('itrepicture', models.ImageField(upload_to='', verbose_name='Re-Picture')),
                ('itmenusel', models.CharField(choices=[('s', '보다'), ('e', '먹다'), ('d', '마시다'), ('sp', '자다')], max_length=8, verbose_name='Menu')),
                ('ittypesel', models.CharField(choices=[('m', 'Must See'), ('ir', '인기지역')], max_length=8, verbose_name='Type')),
                ('itcategorysel', models.CharField(choices=[('r', 'Place'), ('rm', '랜드마크'), ('n', '자연'), ('p', '공원'), ('ri', '박물관'), ('c', '종교'), ('s', '거\x1f리'), ('m', '시장'), ('t', '교통'), ('pp', '공공')], max_length=8, verbose_name='Category')),
                ('itaddress', models.CharField(max_length=64, verbose_name='Address')),
                ('ittell', models.CharField(max_length=64, verbose_name='Tell')),
                ('itwebsite', models.CharField(blank=True, max_length=64, null=True, verbose_name='Website')),
                ('ittraffic', models.CharField(max_length=64, verbose_name='Traffic')),
                ('itintro', models.TextField(blank=True, help_text='이곳을 소개해 주세요.', verbose_name='Introdution')),
                ('itoptime', models.TimeField(verbose_name='Time')),
                ('itopmenu', models.CharField(blank=True, max_length=64, null=True, verbose_name='Open Menu')),
                ('itdate', models.DateField(verbose_name='Date')),
                ('itlocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Rocation')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='City')),
                ('ittag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'InfoTravel',
                'verbose_name_plural': 'InfoTravels',
                'db_table': 'infotravel',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geopt', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpname', models.CharField(max_length=40, verbose_name='Name')),
                ('tpcomment', models.CharField(max_length=64, verbose_name='Comment')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'TravelPlan',
                'verbose_name_plural': 'TravelPlan',
                'db_table': 'travelplan',
            },
        ),
        migrations.CreateModel(
            name='TravelCurator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tctitle', models.CharField(max_length=64, verbose_name='Title')),
                ('tcwritter', models.CharField(max_length=64, verbose_name='Writter')),
                ('ittag', models.CharField(max_length=64, verbose_name='Tag')),
                ('tcwritedate', models.DateField(verbose_name='Write Date')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='City')),
                ('infotravel', models.ManyToManyField(to='cities.InfoTravel', verbose_name='InfoTravels')),
            ],
            options={
                'verbose_name': 'TravelCurator',
                'verbose_name_plural': 'TravelCurators',
                'db_table': 'travelcurator',
            },
        ),
        migrations.CreateModel(
            name='TCImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcimgtitle', models.CharField(max_length=64, verbose_name='Image Title')),
                ('tcimg', models.ImageField(upload_to='', verbose_name='Trave Image')),
                ('travelcurator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.TravelCurator', verbose_name='TravelCurator')),
            ],
            options={
                'verbose_name': 'TCImage',
                'verbose_name_plural': 'TCImages',
                'db_table': 'tcimage',
            },
        ),
        migrations.CreateModel(
            name='POIpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=40, verbose_name='Name')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('travelplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.TravelPlan', verbose_name='TravelPlan')),
            ],
            options={
                'verbose_name': 'POIpoint',
                'verbose_name_plural': 'POIpoint',
                'db_table': 'poipoint',
            },
        ),
        migrations.CreateModel(
            name='InfoBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID number')),
                ('ibname', models.CharField(max_length=64, verbose_name='Name')),
                ('ibrepicture', models.ImageField(upload_to='', verbose_name='Re-Picture')),
                ('ibtitle', models.CharField(max_length=128, verbose_name='Title')),
                ('ibwritter', models.CharField(max_length=64, verbose_name='Writter')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image4')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image5')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'InfoBasic',
                'verbose_name_plural': 'InfoBasics',
                'db_table': 'infobasic',
            },
        ),
    ]
