# Generated by Django 2.2.7 on 2019-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotravel',
            name='test',
            field=models.CharField(default='DEFAULT VALUE', max_length=64, verbose_name='Test'),
        ),
    ]
