# Generated by Django 2.2.4 on 2019-09-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Location'},
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
    ]
