# Generated by Django 2.2.4 on 2019-09-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20190911_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
