# Generated by Django 2.2.7 on 2019-11-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_auto_20191118_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotravel',
            name='part',
            field=models.IntegerField(choices=[(1, '먹다/마시다'), (2, '보다'), (3, '자다'), (4, '사다')], verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='typeit',
            field=models.IntegerField(choices=[(1, 'Must See'), (2, 'Hot')], verbose_name='유형선택'),
        ),
    ]
