# Generated by Django 2.2.7 on 2019-11-19 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_auto_20191119_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parttype', to='cities.InfoTravel')),
            ],
        ),
        migrations.CreateModel(
            name='SleepPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusionko', models.CharField(max_length=64, verbose_name='포함사항(한국어)')),
                ('inclusioneng', models.CharField(max_length=64, verbose_name='포함사항(영어)')),
                ('inclusionven', models.CharField(max_length=64, verbose_name='포함사항(베트남어)')),
                ('roomtypeko', models.CharField(max_length=64, verbose_name='객실타입(한국어)')),
                ('roomtypeeng', models.CharField(max_length=64, verbose_name='객실타입(영어)')),
                ('roomtypeven', models.CharField(max_length=64, verbose_name='객실타입(베트남어)')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Part')),
            ],
        ),
        migrations.CreateModel(
            name='SeePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationtimeko', models.CharField(max_length=64, verbose_name='운영시간(한국어)')),
                ('operationtimeeng', models.CharField(max_length=64, verbose_name='운영시간(영어)')),
                ('operationtimeven', models.CharField(max_length=64, verbose_name='운영시간(베트남어)')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Part')),
            ],
        ),
        migrations.CreateModel(
            name='EatDrinkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biztimeko', models.CharField(max_length=64, verbose_name='영업시간(한국어)')),
                ('biztimeeng', models.CharField(max_length=64, verbose_name='영업시간(영어)')),
                ('biztimeven', models.CharField(max_length=64, verbose_name='영업시간(베트남어)')),
                ('menuko', models.CharField(max_length=64, verbose_name='영업시간(한국어)')),
                ('menueng', models.CharField(max_length=64, verbose_name='영업시간(영어)')),
                ('menuven', models.CharField(max_length=64, verbose_name='영업시간(베트남어)')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Part')),
            ],
        ),
        migrations.CreateModel(
            name='BuyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biztimeko', models.CharField(max_length=64, verbose_name='영업시간(한국어)')),
                ('biztimeeng', models.CharField(max_length=64, verbose_name='영업시간(영어)')),
                ('biztimeven', models.CharField(max_length=64, verbose_name='영업시간(베트남어)')),
                ('saleitemsko', models.CharField(max_length=64, verbose_name='판매상품(한국어)')),
                ('saleitemseng', models.CharField(max_length=64, verbose_name='판매상품(영어)')),
                ('saleitemsven', models.CharField(max_length=64, verbose_name='판매상품(베트남어)')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Part')),
            ],
        ),
    ]
