# Generated by Django 2.2.7 on 2019-11-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_buypart_eatdrinkpart_part_seepart_sleeppart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotravel',
            name='part',
            field=models.CharField(choices=[('EatDrink', '먹다/마시다'), ('See', '보다'), ('Sleep', '자다'), ('Buy', '사다')], max_length=64, verbose_name='구분'),
        ),
    ]
