# Generated by Django 2.2.7 on 2019-11-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_auto_20191119_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buypart',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities.InfoTravel'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities.InfoTravel'),
        ),
        migrations.AlterField(
            model_name='seepart',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities.InfoTravel'),
        ),
        migrations.AlterField(
            model_name='sleeppart',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities.InfoTravel'),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
