# Generated by Django 2.2.7 on 2019-11-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_auto_20191119_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobasic',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='infotravel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='menueng',
            field=models.CharField(max_length=64, verbose_name='대표메뉴(영어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='menuko',
            field=models.CharField(max_length=64, verbose_name='대표메뉴(한국어)'),
        ),
        migrations.AlterField(
            model_name='eatdrinkpart',
            name='menuven',
            field=models.CharField(max_length=64, verbose_name='대표메뉴(베트남어)'),
        ),
    ]
