# Generated by Django 2.2.7 on 2019-11-21 09:25

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cities', '0009_auto_20191120_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelcurator',
            old_name='tcwritter',
            new_name='writter',
        ),
        migrations.RemoveField(
            model_name='travelcurator',
            name='ittag',
        ),
        migrations.RemoveField(
            model_name='travelcurator',
            name='tctitle',
        ),
        migrations.RemoveField(
            model_name='travelcurator',
            name='tcwritedate',
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='created',
            field=models.DateField(null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='infotravel',
            field=models.ManyToManyField(null=True, to='cities.InfoTravel', verbose_name='여행장소'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='introeng',
            field=models.TextField(blank=True, help_text='이곳을 소개해 주세요.', null=True, verbose_name='여행정보(영어)'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='introko',
            field=models.TextField(blank=True, help_text='이곳을 소개해 주세요.', null=True, verbose_name='여행정보(한국어)'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='introven',
            field=models.TextField(blank=True, help_text='이곳을 소개해 주세요.', null=True, verbose_name='여행정보(베트남어)'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='tageng',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='cities.SecondTaggedItem', to='cities.SecondTag', verbose_name='태그(영어)'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='tagko',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그(한국어)'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='tagven',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='cities.ThirdTaggedItem', to='cities.ThirdTag', verbose_name='태그(베트남어)'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='titleeng',
            field=models.CharField(max_length=128, null=True, verbose_name='제목(영어)'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='titleko',
            field=models.CharField(max_length=128, null=True, verbose_name='제목(한국어)'),
        ),
        migrations.AddField(
            model_name='travelcurator',
            name='titleven',
            field=models.CharField(max_length=128, null=True, verbose_name='제목(베트남어)'),
        ),
        migrations.AlterField(
            model_name='infotravel',
            name='part',
            field=models.CharField(choices=[('Eat', '먹다'), ('Drink', '마시다'), ('See', '보다'), ('Sleep', '자다'), ('Buy', '사다')], max_length=64, verbose_name='구분'),
        ),
    ]
