# Generated by Django 2.2.7 on 2019-11-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20191122_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcimage',
            name='travelcurator',
        ),
        migrations.AlterField(
            model_name='travelcurator',
            name='infotravel',
            field=models.ManyToManyField(to='cities.InfoTravel', verbose_name='여행장소 추가'),
        ),
    ]
