# Generated by Django 2.2.7 on 2019-11-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0014_auto_20191125_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcimage',
            name='tcimgtitle',
        ),
        migrations.RemoveField(
            model_name='travelcurator',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='travelcurator',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='travelcurator',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='travelcurator',
            name='picture4',
        ),
        migrations.AddField(
            model_name='poipoint',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='poipoint',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='poipoint',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='poipoint',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture2'),
        ),
        migrations.AddField(
            model_name='tcimage',
            name='travelcurator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.TravelCurator', verbose_name='TravelCurator'),
        ),
    ]
