# Generated by Django 2.2.7 on 2019-11-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_auto_20191125_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcimage',
            options={'verbose_name': '대표이미지', 'verbose_name_plural': '대표이미지'},
        ),
    ]
