# Generated by Django 2.2.7 on 2019-11-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191121_1825'),
        ('cities', '0017_auto_20191126_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcimage',
            options={'verbose_name': '대표이미지(TravelCulator)', 'verbose_name_plural': '대표이미지(TravelCulator)'},
        ),
        migrations.RemoveField(
            model_name='infotravel',
            name='category',
        ),
        migrations.AddField(
            model_name='infotravel',
            name='category',
            field=models.ManyToManyField(to='common.CSmall'),
        ),
    ]
