# Generated by Django 2.2.7 on 2019-11-18 07:47

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.CharField(max_length=64, verbose_name='대분류')),
                ('medium', models.CharField(max_length=64, verbose_name='중분류')),
                ('small', models.CharField(max_length=64, verbose_name='소분류')),
            ],
        ),
        migrations.CreateModel(
            name='CLarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('categorylarge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.CLarge')),
            ],
        ),
        migrations.CreateModel(
            name='CSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('categorylarge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.CLarge')),
                ('categorymedium', smart_selects.db_fields.GroupedForeignKey(group_field='categorylarge', on_delete=django.db.models.deletion.CASCADE, to='common.CMedium')),
            ],
        ),
    ]
