# Generated by Django 2.2.7 on 2019-11-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices1', models.IntegerField(choices=[(1, '먹다/마시다'), (2, '보다'), (3, '자다'), (4, '사다')])),
            ],
        ),
    ]
