# Generated by Django 2.2.7 on 2019-11-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_tmptest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptest',
            name='choices1',
            field=models.IntegerField(choices=[(1, '먹다/마시다'), (2, '보다'), (3, '자다'), (4, '사다')], verbose_name='choices Large'),
        ),
    ]
