# Generated by Django 2.2.7 on 2019-11-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20191119_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tmptest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.TmpTest')),
            ],
        ),
    ]
