# Generated by Django 2.2.7 on 2019-11-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_tmpadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptest',
            name='choices1',
            field=models.IntegerField(choices=[('EatDrink', '먹다/마시다'), ('See', '보다'), ('Sleep', '자다'), ('Buy', '사다')], verbose_name='choices Large'),
        ),
    ]
