# Generated by Django 2.2.7 on 2019-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20191119_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptest',
            name='choices1',
            field=models.IntegerField(choices=[('Eat', '먹다'), ('Drink', '마시다'), ('See', '보다'), ('Sleep', '자다'), ('Buy', '사다')], verbose_name='choices Large'),
        ),
    ]
